name: rust

on:
  push:
    branches:
        - "master"
  pull_request:
    branches:
        - "master"

jobs:
  build:
    runs-on: "ubuntu-latest"
    name: "Prodution"
    steps:
        - uses: actions/checkout@v2
        - name: checkout
          run: cargo build --release --verbose